# Dev Log

## 4/12/2026 First Entry

First dev log entry! Although this project started almost two years ago, I have a few months worth of work into it. So far, the project has focused on OpenGl: understanding the basic rendering pipeline, meshes, basic linear algebra etc. I have also worked on the build system to understand CMake and Conan, which I believe are the best build related tools in C++ development. Nix integration being the last step in that process to encapsulate the system package dependencies not managed by CMake or Conan. 

At this point in the project, I can construct and render basic rectangular and spherical meshes. I have yet to do any kind of simulation in those meshes. I describe potential next steps in [this commit](https://github.com/clementfaisandier/sim-world/issues/3). My current focus is to implement some basic simulations. The big challenge there being my limited knowledge in ODEs and experience with Physical simulations.

For the sake of my sanity, I will start building simulations with my very limited knowledge. These will often not be right. But at least it will be fun to derive from my understanding of physics and math. Then I will be able to compare with the textbooks, and learn the proper math and physics through experimentation and failure.

To start, I will model 2D fluids using my grid mesh builder. This mesh builder could be improved render-wise using instanced and deffered rendering, but that will be a lesson for another day, for now the un-optimized method will do.

There is however, value in implementing visuals that convey the movement of a fluid. This can be done using particles or by adding arrows that point in the direction the fluid is moving, and who's color or lenght represent the speed of the fluid.

I have started documenting these models: [Incompressible Fluids](incompressible-fluid.qmd).

## 4/13/2026

Today I wrote the section **Moving a Fluid**, discussing the mesh representation of a fluid, and why it is acceptable to assume a cell only interacts with it's in-axis neighbors (so no diagonal neighbor interaction).

This was very interesting and satisfying, and of course the next step is to define the interactions between these cells. However, I realized something: because Newton's laws of motion led to Bernoulli's principle, which led to Euleur's equations for fluids which led to the Navier-Stokes equations of fluid dynamics.

This means I should start with Newton's laws. How do kinetic physics of discrete particles lead to fluid mechanics which describe continuums? I have a general understanding of the idea, but I should implement them step by step.

Therefore the plan should be to:

- Create fluid simulation using discrete particles governed by Newtonian physics.
  - Added bonus: this can quickly be converted to a solar system simulation by adding gravity and lowering the density of particles.
- Go for Euleur's equations.
- Then finally Navier-Stokes.
- Can I make a simulation that seamlessly blends the three (for educational purposes/style points)?
